### ISSUE TITLE
NotImplementedError: cannot attach attributes to nodes of type '<class 'pycparser.c_ast.FuncDecl'>'

### ISSUE THREAD

**Issue by vijunag** [inducer/pycparserext#13]
Parserext fails when GCC attributes are attached as suffixes instead of prefix. Is this a known issue ?
At the end of this note is a small C snippet that can be used to reproduce the below crash.

BackTrace:
Traceback (most recent call last):
  File "gcc_E.py", line 37, in <module>
    main(sys.argv[1:])
  File "gcc_E.py", line 33, in main
    cpp_args=cpp_args)
  File "/root/pycparser/pycparser/pycparser/__init__.py", line 96, in parse_file
    return parser.parse(text)
  File "/root/pycparser/pycparserext-master/pycparserext/ext_c_parser.py", line 64, in parse
    return self.cparser.parse(text, lexer=self.clex, debug=debuglevel)
  File "/root/pycparser/pycparser/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/root/pycparser/pycparser/pycparser/ply/yacc.py", line 971, in parseopt_notrack
    p.callable(pslice)
  File "/root/pycparser/pycparserext-master/pycparserext/ext_c_parser.py", line 245, in p_declarator_1
    % type(p[1]))
NotImplementedError: cannot attach attributes to nodes of type '<class 'pycparser.c_ast.FuncDecl'>

Code snippet:
#include <stdio.h>
extern void int happy(void) __attribute__((unused));
int main()
{
}

**Comment by vijunag** [comment]
Is this a plausible patch for the above fix ?

--- /root/2	2016-03-15 00:29:11.000000000 -0700
+++ ./pycparserext/ext_c_parser.py	2016-03-15 00:28:26.000000000 -0700
@@ -238,6 +238,9 @@
             if isinstance(p[1], c_ast.ArrayDecl):
                 p[1].type = TypeDeclExt.from_pycparser(p[1].type)
                 p[1].type.attributes = p[2]
+            elif isinstance(p[1], c_ast.FuncDecl):
+                p[1].type = TypeDeclExt.from_pycparser(p[1].type)
+                p[1].type.attributes = p[2]
             elif not isinstance(p[1], c_ast.TypeDecl):
                 raise NotImplementedError(
                         "cannot attach attributes to nodes of type '%s'"

**Comment by inducer** [comment]
Looks good. Thanks for the patch!
