### ISSUE TITLE
pycparser.plyparser.ParseError: ?: Invalid declaration

### ISSUE THREAD

**Issue by vijunag** [inducer/pycparserext#14]
pycparserext fails to reduce function declarations of the form 
void* foo(int a, int b) __attribute__((nonnull(1));

The script crashed with the following bt:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pycparserext/ext_c_parser.py", line 64, in parse
    return self.cparser.parse(text, lexer=self.clex, debug=debuglevel)
  File "/home/vijay/script/pycparser/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/home/vijay/script/pycparser/pycparser/ply/yacc.py", line 971, in parseopt_notrack
    p.callable(pslice)
  File "/home/vijay/script/pycparser/pycparser/c_parser.py", line 638, in p_decl_body
    typedef_namespace=True)
  File "/home/vijay/script/pycparser/pycparser/c_parser.py", line 389, in _build_declarations
    self._parse_error('Invalid declaration', coord)
  File "/home/vijay/script/pycparser/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: ?: Invalid declaration

A simple script to reproduce the issue:
from pycparserext.ext_c_parser import GnuCParser
src="""void* memcpy(const void *a, const void *b, int len) __attribute__((nonnull(1))) __attribute__((nonnull(2)));"""
p = GnuCParser()
p.parse(src).show()

However the parser succeeds If the declaration doesn't contain pointer as return type 
>>> src="""void foo(int a, int b) __attribute__((nonnull(1)));"""
>>> p.parse(src).show()
FileAST:
  Decl: foo, [], [], []
    FuncDecl:
      ParamList:
        Decl: a, [], [], []
          TypeDecl: a, []
            IdentifierType: ['int']
        Decl: b, [], [], []
          TypeDecl: b, []
            IdentifierType: ['int']
      TypeDeclExt: foo, []
        IdentifierType: ['void']

I haven't found time to figure out the exact production that is reducing the expression in the above two cases. It will be great if you can fix this or point out the error.

**Comment by inducer** [comment]
```
void* foo(int a, int b) attribute((nonnull(1));
```
looks like it has unbalanced parens.

Unrelatedly, please use triple-backquotes to quote your code on Github, so it doesn't come out a mess like it does now.

**Comment by vijunag** [comment]
Perhaps a balanced parenthesis still has a problem.

**Comment by vijunag** [comment]
I finally managed to write a production to reduce the expressions of above form.
Below is the patch that reduces statements 
declarator:  pointer direct_declarator attributes_opt
                 | pointer attributes_opt direct_declarator

The generators are crashing while emitting statements of the above form. Can you please help me fix this ?
http://pastebin.com/WKz9d4PG

**Comment by inducer** [comment]
Thanks for the patch! I've merged what I believe to be a fixed version.

**Comment by vijunag** [comment]
Please note that c generator isn't working for funcs with attributes.

**Comment by vijunag** [comment]
Can you provide commit access as I have added couple of Gnu C extensions ?

**Comment by inducer** [comment]
> Please note that c generator isn't working for funcs with attributes.

Could you provide a test?

> Can you provide commit access as I have added couple of Gnu C extensions ?

Just fork the repo and send a pull request.

**Comment by vijunag** [comment]
I have already added the tests in the test file.

**Comment by inducer** [comment]
All those pass.
