### ISSUE TITLE
test/test_pycparserext.py L244 test_array_attributes lost array dimension

### ISSUE THREAD

**Issue by windclarion** [inducer/pycparserext#57]
I work on python3.8.6 x64 version,  windows 7 64bit OS, I use pip to install pycparser 2.20, PLY 3.11 ,  then git clone pycparserext and python setup.py install.  Is there anything I missed?

**Comment by windclarion** [comment]
I found v2020.1 is ok, so I try each commit, the problem is introduced in commit a65cda4210fb477a10a680726a0b8a444ee6814a, Added support for Asm labels

**Comment by inducer** [comment]
If you're reporting a test failure, then almost certainly something in your environment. As you can see from the [CI](https://github.com/inducer/pycparserext/actions?query=workflow%3ACI), every pushed commit is automatically tested and has passed the test suite. In addition, the code is automatically tested every week against the then-current versions of upstream packages.

**Comment by inducer** [comment]
(If you're not reporting a test failure, please post an MWE of the problem you observe.)

**Comment by windclarion** [comment]
Thank you for your suggestion, I will check the CI and found my env's problem
